"""benchmark/results_<tag>.json -> benchmark/REPORT.md (tables only; every number regenerable)."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def pct(x):
    return "n/a" if x is None else f"{x * 100:.1f}%"


def main(tag="main"):
    R = json.loads((ROOT / "benchmark" / f"results_{tag}.json").read_text())
    fl = json.loads((ROOT / "benchmark" / "fixloop_eval.json").read_text()) if (ROOT / "benchmark" / "fixloop_eval.json").exists() else None
    syn = json.loads((ROOT / "benchmark" / "synthetic_damage.json").read_text()) if (ROOT / "benchmark" / "synthetic_damage.json").exists() else None
    L = []
    w = L.append
    w("# Benchmark report\n")
    w(f"Generated by `python scripts/benchmark.py` then `python scripts/make_report.py` (tag `{tag}`). "
      "Runs: `benchmark/runs/{tag}/*.json|png`.\n".replace("{tag}", tag))
    w("**Ground truth caveat.** The sample captures came without laser or tape measurements. The LiDAR gates are scored as "
      "*repeatability between two captures*, and the video and photo gates as *agreement with the LiDAR tier of the same "
      "capture*. Absolute accuracy against a laser is **NOT MEASURED** anywhere in this report.\n")

    w("## Gates\n")
    w("| Gate | Requirement | Measured | Status |")
    w("|---|---|---|---|")
    rep = R.get("repeatability_lidar_floor_vs_ceil", {})
    w(f"| Repeatability (LiDAR) | 1 cm / 0.5% per wall | {pct(rep.get('walls_within_1cm_or_0p5pct'))} of "
      f"{rep.get('walls_compared')} walls; median {rep.get('wall_abs_diff_median_cm')} cm | FAIL (fix loop: docs/FIX_LOOP.md) |")
    cp = rep.get("ceiling_pairs") or []
    w(f"| Ceiling height spread | ≤ 1 cm across captures | {len(cp)} room pairs with both ceilings observed | "
      f"{'NOT MEASURABLE (floor_only never scanned ceilings)' if not cp else ''} |")
    w("| Ceiling height accuracy | ≤ 1.5 cm vs laser | — | NOT MEASURED (no laser) |")
    w(f"| Opening widths | ≤ 2 cm on ≥ 85% vs laser | cross-capture: {rep.get('openings_matched')} openings matched of "
      f"{rep.get('openings_a')}/{rep.get('openings_b')}; {pct(rep.get('opening_width_diff_le_2cm'))} agree within 2 cm | "
      "NOT MEASURED vs laser; detection consistency is low |")
    da = R.get("drift_ablation", {})
    if da:
        c = da.get("ceil", {})
        w(f"| Drift accountability | stated method + on/off ablation | pose graph, {c.get('loop_closures')} loop closures; "
          f"ghost-wall area {c.get('ghost_wall_area_off')} → {c.get('ghost_wall_area_on')} m² | DONE |")
    for k, name, g in (("video_vs_lidar_V_room", "Video wall lengths (single_room)", "±3%"),
                       ("video_vs_lidar_V_floor", "Video wall lengths (floor_only)", "±3%"),
                       ("video_vs_lidar_V_ceil", "Video wall lengths (with_ceiling)", "±3%"),
                       ("photos_vs_lidar_P_ceil", "Photo wall lengths (with_ceiling)", "±8%")):
        v = R.get(k)
        if v:
            w(f"| {name} | {g}, calibrated | {pct(v.get('wall_within_gate'))} within {g} "
              f"({v.get('walls_compared')} walls, median err {v.get('wall_rel_err_median_pct')}%); CI coverage "
              f"{pct(v.get('ci95_coverage'))} | {'PASS' if (v.get('wall_within_gate') or 0) >= 0.85 else 'FAIL'} |")
    ps = R.get("photo_stitch_P_ceil")
    if ps:
        w(f"| Photo whole-property stitch | correct adjacency, no overlaps, footprint ±8% | "
          f"{ps['rooms_recovered']}/{ps['room_folders']} rooms; adjacency P={ps['adjacency_precision']} "
          f"R={ps['adjacency_recall']}; overlaps {len(ps['overlaps'])}; footprint err {ps['footprint_err_pct']}% | "
          f"{'PASS' if ps['gate_pass'] else 'FAIL'} |")
    w("")

    w("## Repeatability (LiDAR, same tier, two captures)\n")
    w("| Pair | Plan IoU | Rooms matched | Walls compared | Within 1 cm/0.5% | Median abs diff | p90 |")
    w("|---|---|---|---|---|---|---|")
    for k, v in R.items():
        if k.startswith("repeatability"):
            w(f"| {k.replace('repeatability_lidar_', '')} | {v['plan_iou']} | {v['matched_rooms']} | {v['walls_compared']} | "
              f"{pct(v['walls_within_1cm_or_0p5pct'])} | {v['wall_abs_diff_median_cm']} cm | {v['wall_abs_diff_p90_cm']} cm |")
    w("\nRoom areas (m²), with_ceiling vs floor_only: " + ", ".join(
        f"{r}: {a} / {b}" for r, a, b in rep.get("area_pairs", [])) + "\n")
    if fl:
        w("Fix-loop variants on the same fused clouds (`scripts/fixloop_eval.py`):\n")
        w("| Wall fit | Within gate | Median | p90 |")
        w("|---|---|---|---|")
        for m in ("legacy", "high", "planes"):
            if m in fl:
                v = fl[m]
                w(f"| {m} | {pct(v['walls_within_1cm_or_0p5pct'])} | {v['wall_abs_diff_median_cm']} cm | {v['wall_abs_diff_p90_cm']} cm |")
        w("")

    w("## Drift ablation (poses as-is vs pose-graph corrected)\n")
    w("| Capture | Footprint off → on (m²) | Rooms off → on | Ghost-wall area off → on (m²) | Loop closures | Mean / max correction |")
    w("|---|---|---|---|---|---|")
    for cap, v in da.items():
        w(f"| {cap} | {v['footprint_off']:.2f} → {v['footprint_on']:.2f} | {v['rooms_off']} → {v['rooms_on']} | "
          f"{v['ghost_wall_area_off']} → {v['ghost_wall_area_on']} | {v['loop_closures']} | "
          f"{v['mean_correction_m']:.3f} / {v['max_correction_m']:.3f} m |")
    w("\nGhost-wall area is the area of 2.5 cm plan cells holding wall returns 0.3–1.9 m above the floor. Drifted, doubled walls inflate it.\n")

    w("## Cross-tier agreement and calibration (reference = LiDAR tier of the same capture)\n")
    w("| Run | Plan IoU | Rooms (ref / tier / matched) | Walls | Median abs rel err | Within gate | 95% CI coverage | Matched footprint ref → tier |")
    w("|---|---|---|---|---|---|---|---|")
    for k, v in R.items():
        if k.startswith(("video_vs", "photos_vs")):
            if not v.get("walls_compared"):
                w(f"| {k} | {v.get('plan_iou')} | — | 0 | — | — | — | — |")
                continue
            w(f"| {k} | {v['plan_iou']} | {v['rooms_ref']} / {v['rooms_tier']} / {v['rooms_matched']} | {v['walls_compared']} | "
              f"{v['wall_rel_err_median_pct']}% | {pct(v['wall_within_gate'])} (±{v['gate_rel_pct']:.0f}%) | "
              f"{pct(v['ci95_coverage'])} | {v['matched_footprint_ref_m2']} → {v['matched_footprint_tier_m2']} "
              f"({v['matched_footprint_err_pct']}%) |")
    w("\nCI coverage is the fraction of walls where |tier − LiDAR| ≤ 1.96·sqrt(σ_tier² + σ_lidar²). Well calibrated is about 95%.\n")

    if ps:
        w("## Photo-tier whole-property stitch\n")
        w(f"- Room folders: {ps['room_folders']}; rooms recovered: {ps['rooms_recovered']}")
        w(f"- Reference adjacency (among supplied folders): {ps['adjacency_ref']}")
        w(f"- Found adjacency: {ps['adjacency_found']}")
        w(f"- Overlaps: {ps['overlaps'] or 'none'}")
        w(f"- Footprint (recovered rooms): {ps['footprint_tier_m2']} m² vs reference {ps['footprint_ref_m2']} m² "
          f"({ps['footprint_err_pct']}%), within CI: {ps['footprint_in_ci']}\n")

    if syn:
        w("## Damage (SYNTHETIC injection: the data has no staged damage)\n")
        w(f"Wall `{syn['wall']}`. Truth: " + "; ".join(f"{t['cls']} {t['w']:.2f}×{t['h']:.2f} m" for t in syn["truth"]))
        w("\n| Detected | Surface | Width × height (m) | 95% CI width | Views |")
        w("|---|---|---|---|---|")
        for d in syn["detected"]:
            w(f"| {d['cls']} | {d['surface']} | {d['w']} × {d['h']} | {d['w_ci']} | {d['frames']} |")
        if not syn["detected"]:
            w("| none | | | | |")
        w(f"\nRules fired: {[c['rule'] for c in syn['concealed']]}; scope items: {len(syn['scope'])}\n")

    w("## Timing (seconds, 12-thread laptop CPU, no GPU)\n")
    w("| Run | Total | Stages |")
    w("|---|---|---|")
    for k, v in R.get("timing_s", {}).items():
        if v:
            w(f"| {k} | {v.get('total')} | " + ", ".join(f"{a} {b}" for a, b in v.items() if a != "total") + " |")
    w("")
    w("## Head-to-head vs a consumer app\n")
    w("NOT DONE. It needs a Polycam or magicplan scan of the same rooms on an iPhone, and we had neither the device nor "
      "access to the sample apartment. `propscan/compare.py` already registers and matches any two plans, so an exported "
      "magicplan/Polycam plan converted to the schema could be scored with `repeatability()` unchanged.\n")
    (ROOT / "benchmark" / "REPORT.md").write_text("\n".join(L), encoding="utf-8")
    print("wrote benchmark/REPORT.md")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "main")
